### ISSUE TITLE
Fix controller mapping

### ISSUE THREAD

**Issue by jonasmuriboe** [hbirchtree/it2901-project#15]
Test different controller mappings and implement it

**Comment by Sti2nd** [comment]
New controller mapping
- Teleport on grip 1 and 2 on left and right hand
- Menu on right shoulder
- Laser on left shoulder button
- click on face button 1 right

**Comment by Sti2nd** [comment]
Me and @Camorte tested this, Ekaterina liked having teleport on face button. The only available button to use for select/click in menu are the grip buttons, but I do not think this is a very intuitive way. Since we will have to remap the controllers again when making the new menus, we decided it is pointless to change any controller mapping this sprint.
